"""add manufacturer reference table

Revision ID: 121ee918cff8
Revises: ec518f72d312
Create Date: 2026-09-05 19:59:02.931670
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '121ee918cff8'
down_revision: Union[str, Sequence[str], None] = 'ec518f72d312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturer_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer_address', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturer_references_manufacturer_name'), 'manufacturer_references', ['manufacturer_name'], unique=False)
    op.create_index(op.f('ix_manufacturer_references_product_id'), 'manufacturer_references', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manufacturer_references_product_id'), table_name='manufacturer_references')
    op.drop_index(op.f('ix_manufacturer_references_manufacturer_name'), table_name='manufacturer_references')
    op.drop_table('manufacturer_references')
    # ### end Alembic commands ###

