"""add MRP reference and tamper findings

Revision ID: 4a31ceda9737
Revises: 0c3b0136dd9e
Create Date: 2026-09-04 09:15:49.131889
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4a31ceda9737'
down_revision: Union[str, Sequence[str], None] = '0c3b0136dd9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_mrp_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('pack_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('pack_unit', sa.String(length=30), nullable=True),
    sa.Column('variant', sa.String(length=150), nullable=True),
    sa.Column('reference_mrp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_mrp_references_product_id'), 'product_mrp_references', ['product_id'], unique=False)
    op.create_table('mrp_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('declared_mrp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reference_mrp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_status', sa.String(length=30), nullable=False),
    sa.Column('difference_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reference_source', sa.Text(), nullable=True),
    sa.Column('tamper_status', sa.String(length=30), nullable=False),
    sa.Column('tamper_risk_score', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['inspection_images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mrp_findings_image_id'), 'mrp_findings', ['image_id'], unique=False)
    op.create_index(op.f('ix_mrp_findings_inspection_id'), 'mrp_findings', ['inspection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mrp_findings_inspection_id'), table_name='mrp_findings')
    op.drop_index(op.f('ix_mrp_findings_image_id'), table_name='mrp_findings')
    op.drop_table('mrp_findings')
    op.drop_index(op.f('ix_product_mrp_references_product_id'), table_name='product_mrp_references')
    op.drop_table('product_mrp_references')
    # ### end Alembic commands ###
