"""create rule repository

Revision ID: dab3f6bef92d
Revises: 121ee918cff8
Create Date: 2026-09-07 09:55:38.240376
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'dab3f6bef92d'
down_revision: Union[str, Sequence[str], None] = '121ee918cff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=False),
    sa.Column('authority', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulations_code'), 'regulations', ['code'], unique=True)
    op.create_index(op.f('ix_regulations_status'), 'regulations', ['status'], unique=False)
    op.create_table('rule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regulation_id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('rule_number', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approval_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regulation_id', 'rule_code', 'version', name='uq_rule_versions_regulation_code_version')
    )
    op.create_index(op.f('ix_rule_versions_approval_status'), 'rule_versions', ['approval_status'], unique=False)
    op.create_index(op.f('ix_rule_versions_effective_from'), 'rule_versions', ['effective_from'], unique=False)
    op.create_index(op.f('ix_rule_versions_effective_to'), 'rule_versions', ['effective_to'], unique=False)
    op.create_index(op.f('ix_rule_versions_regulation_id'), 'rule_versions', ['regulation_id'], unique=False)
    op.create_index(op.f('ix_rule_versions_rule_code'), 'rule_versions', ['rule_code'], unique=False)
    op.create_index(op.f('ix_rule_versions_rule_number'), 'rule_versions', ['rule_number'], unique=False)
    op.create_index(op.f('ix_rule_versions_status'), 'rule_versions', ['status'], unique=False)
    op.create_table('rule_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_version_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=30), nullable=False),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('expected_unit', sa.String(length=30), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('failure_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_checks_field_name'), 'rule_checks', ['field_name'], unique=False)
    op.create_index(op.f('ix_rule_checks_rule_version_id'), 'rule_checks', ['rule_version_id'], unique=False)
    op.create_index(op.f('ix_rule_checks_severity'), 'rule_checks', ['severity'], unique=False)
    op.create_table('rule_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_version_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=30), nullable=False),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('logical_group', sa.Integer(), nullable=False),
    sa.Column('condition_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_conditions_field_name'), 'rule_conditions', ['field_name'], unique=False)
    op.create_index(op.f('ix_rule_conditions_rule_version_id'), 'rule_conditions', ['rule_version_id'], unique=False)
    op.create_table('rule_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_version_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('source_title', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_sources_rule_version_id'), 'rule_sources', ['rule_version_id'], unique=False)
    op.create_index(op.f('ix_rule_sources_source_type'), 'rule_sources', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_sources_source_type'), table_name='rule_sources')
    op.drop_index(op.f('ix_rule_sources_rule_version_id'), table_name='rule_sources')
    op.drop_table('rule_sources')
    op.drop_index(op.f('ix_rule_conditions_rule_version_id'), table_name='rule_conditions')
    op.drop_index(op.f('ix_rule_conditions_field_name'), table_name='rule_conditions')
    op.drop_table('rule_conditions')
    op.drop_index(op.f('ix_rule_checks_severity'), table_name='rule_checks')
    op.drop_index(op.f('ix_rule_checks_rule_version_id'), table_name='rule_checks')
    op.drop_index(op.f('ix_rule_checks_field_name'), table_name='rule_checks')
    op.drop_table('rule_checks')
    op.drop_index(op.f('ix_rule_versions_status'), table_name='rule_versions')
    op.drop_index(op.f('ix_rule_versions_rule_number'), table_name='rule_versions')
    op.drop_index(op.f('ix_rule_versions_rule_code'), table_name='rule_versions')
    op.drop_index(op.f('ix_rule_versions_regulation_id'), table_name='rule_versions')
    op.drop_index(op.f('ix_rule_versions_effective_to'), table_name='rule_versions')
    op.drop_index(op.f('ix_rule_versions_effective_from'), table_name='rule_versions')
    op.drop_index(op.f('ix_rule_versions_approval_status'), table_name='rule_versions')
    op.drop_table('rule_versions')
    op.drop_index(op.f('ix_regulations_status'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_code'), table_name='regulations')
    op.drop_table('regulations')
    # ### end Alembic commands ###
