"""add product barcode table

Revision ID: ec518f72d312
Revises: 671bf4077bb9
Create Date: 2026-09-05 18:29:28.930152
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'ec518f72d312'
down_revision: Union[str, Sequence[str], None] = '671bf4077bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_barcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('barcode_value', sa.String(length=32), nullable=False),
    sa.Column('barcode_type', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_barcodes_barcode_value'), 'product_barcodes', ['barcode_value'], unique=False)
    op.create_index(op.f('ix_product_barcodes_product_id'), 'product_barcodes', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_barcodes_product_id'), table_name='product_barcodes')
    op.drop_index(op.f('ix_product_barcodes_barcode_value'), table_name='product_barcodes')
    op.drop_table('product_barcodes')
    # ### end Alembic commands ###

